type: object

required: [namespace, version, elements]
properties:
  namespace: { type: string }

  version:
    type: object
    required: [ref, pubdate]
    additionalProperties: false
    properties:
      ref: { type: string }
      pubdate: { type: string }

  elements:
    type: object
    additionalProperties:
      type: object
      required: [ref, description, attributes, interface, events]
      additionalProperties: false
      properties:
        ref: { type: string }
        description: { type: string }
        events: 
          type: object
          additionalProperties:
            type: object
            additionalProperties: false
            properties:
              ref: { type: string }
              description: { type: string }
              interface: { type: string }
        interface: { type: string }
        attributes:
          type: object
          additionalProperties:
            type: object
            required: [ref, description, values]
            additionalProperties: false
            properties:
              ref: { type: string }
              description: { type: string }
              values: {}
            
      