name: Validate

on: [push, pull_request]

jobs:
  schemaCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Upgrade NPM
        run: npm install -g npm

      - name: Install dependencies
        run: npm ci
      
      - run: npm run check:all